
package cur.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Apr 14 19:17:47 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addCurrency", namespace = "http://service.webservice.cur/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCurrency", namespace = "http://service.webservice.cur/", propOrder = {"newCurrencyName", "newCurrencyValue"})

public class AddCurrency {

    @XmlElement(name = "newCurrencyName")
    private java.lang.String newCurrencyName;
    @XmlElement(name = "newCurrencyValue")
    private double newCurrencyValue;

    public java.lang.String getNewCurrencyName() {
        return this.newCurrencyName;
    }

    public void setNewCurrencyName(java.lang.String newNewCurrencyName)  {
        this.newCurrencyName = newNewCurrencyName;
    }

    public double getNewCurrencyValue() {
        return this.newCurrencyValue;
    }

    public void setNewCurrencyValue(double newNewCurrencyValue)  {
        this.newCurrencyValue = newNewCurrencyValue;
    }

}

