
package cur.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Apr 14 19:17:47 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "conversion", namespace = "http://service.webservice.cur/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conversion", namespace = "http://service.webservice.cur/", propOrder = {"currencyInput", "typeInput", "typeOutput"})

public class Conversion {

    @XmlElement(name = "currencyInput")
    private double currencyInput;
    @XmlElement(name = "typeInput")
    private java.lang.String typeInput;
    @XmlElement(name = "typeOutput")
    private java.lang.String typeOutput;

    public double getCurrencyInput() {
        return this.currencyInput;
    }

    public void setCurrencyInput(double newCurrencyInput)  {
        this.currencyInput = newCurrencyInput;
    }

    public java.lang.String getTypeInput() {
        return this.typeInput;
    }

    public void setTypeInput(java.lang.String newTypeInput)  {
        this.typeInput = newTypeInput;
    }

    public java.lang.String getTypeOutput() {
        return this.typeOutput;
    }

    public void setTypeOutput(java.lang.String newTypeOutput)  {
        this.typeOutput = newTypeOutput;
    }

}

