
package cur.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Apr 14 19:17:47 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "conversionResponse", namespace = "http://service.webservice.cur/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conversionResponse", namespace = "http://service.webservice.cur/")

public class ConversionResponse {

    @XmlElement(name = "monnaieSortie")
    private java.lang.String monnaieSortie;

    public java.lang.String getMonnaieSortie() {
        return this.monnaieSortie;
    }

    public void setMonnaieSortie(java.lang.String newMonnaieSortie)  {
        this.monnaieSortie = newMonnaieSortie;
    }

}

