
package cur.webservice.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Wed Apr 14 19:17:47 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "updateCurrency", namespace = "http://service.webservice.cur/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "updateCurrency", namespace = "http://service.webservice.cur/", propOrder = {"currencyName", "newRate"})

public class UpdateCurrency {

    @XmlElement(name = "currencyName")
    private java.lang.String currencyName;
    @XmlElement(name = "newRate")
    private double newRate;

    public java.lang.String getCurrencyName() {
        return this.currencyName;
    }

    public void setCurrencyName(java.lang.String newCurrencyName)  {
        this.currencyName = newCurrencyName;
    }

    public double getNewRate() {
        return this.newRate;
    }

    public void setNewRate(double newNewRate)  {
        this.newRate = newNewRate;
    }

}

